name: do_an
description: Ứng dụng chia sẻ công thức nấu ăn Việt Nam.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_animate: ^4.1.1
  lottie: ^3.3.1
  smooth_page_indicator: ^1.1.0
  flutter_carousel_widget: ^3.1.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  share_plus: ^10.1.4
  flutter_staggered_grid_view: ^0.7.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.7
  firebase_database: ^11.3.5
  firebase_storage: ^12.4.6
  path: ^1.9.1
  permission_handler: ^12.0.0+1
  video_player: ^2.10.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    # - assets/lottie/
